language: R
sudo: no
cache: packages
after_success: Rscript -e "packagedocs::deploy_travis()"
env:
  global:
    secure: MpG0BXx0XxPRljLz44FBYBa77SibLGCqBgJ5EGfNdlZ8ZKybL0GDSBj1wwnO4czQMPpKHQqASomdWaMkVI0L7cLulzJYWR71nu7k5uMmFOQjbsLFg0XzLHBb9lV5XHr1c9j5wU1t1gc10iZ6AUdryyQ+8HFCPLxbhBWY6vuRCJCpPfkheJqbMUvEQ0xUYYrerRhxoevwokM56xwX377ZuMesbw4Lde9nBNbZ1l9Cs0ixb9/kLZpf8dzeJlLHLMKH+Muq4vyvFen+deGVKSCj1Z9leqkbzOQEE87uVtoxjHG1DcBOO2xIpwZCxB7qGjSdBX0GNaK6TwtAsTxmR+ZKUmnwIl0v8qFZH1jRckYM9aMwvVWO9Siqcl6VV1PhlRD0zmwR13zBpsGrd37VobxTssV4bRarfE6PJ1S56Fox04DI83eSWPv8QRo20tu65vxR6hTegZVVKPCl5Z3pizaCG7hc3JSPaGHi8EhuLg0aInvxeRT9OwbBT/XcoJqvPZu/bKjwt1E15NcJhl7iz7S0fngsOz9PCRDtoee8lYHUCxQyYd1JlCA3vKmrmYmBm3/JAJ2Tgj0HXFeDX21pDBmLjTiWBduSQ4WqYYTWCYn3QohvvcCriNbUBOtorMUQuJpFoHO6AcItBtdBar0hE1NLfUDRRYbnc5ljucyJFVBP83M=
